version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ride_requests_db
      POSTGRES_USER: ride_user
      POSTGRES_PASSWORD: ride_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
